### ISSUE TITLE
0.6.6 update breaks on linux-like systems with custom libc implementations

### ISSUE THREAD

**Issue by reuvenpo** [jeromefroe/lru-rs#114]
This commit (https://github.com/jeromefroe/lru-rs/commit/2663a8041307f66e5b0a5979fe0d2147d5556474) included in the latest `0.6.6` release bumps the version of `hashbrown` from `0.9` to `0.11`, which bumps the version of `ahash` from `0.4` to `0.7`, which in turn adds a dependency on `libc` for `linux` targets by pulling in [`getrandom`](https://github.com/tkaitchuck/aHash/blob/master/Cargo.toml#L69).

The `x86_64-unknown-linux-sgx` target (created by [teaclave](https://github.com/apache/incubator-teaclave-sgx-sdk)) has a custom version of `libc` called [`sgx_libc`](https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/sgx_libc) and just replacing the package that `ahash` uses doesn't resolve the issue as they are different versions of `libc` which are incompatible (it looks like `ahash` is trying to use symbols that are not available in `sgx_libc`).

I understand that you are not the developer of these dependencies, but the commit linked above means that i cannot use that latest version of `lru-rs` in my project. I think that adding a few feature flags to `ahash` and `hashbrown` can help resolve this issue.

Thank you for your time if you look into it!

**Comment by jeromefroe** [comment]
Hi @reuvenpo! Sorry for the issues with the latest update. I'd be happy to update the crate to make `getrandom` optional, but it seems like we'd need to update the `ahash` and `hashbrown` crates first. Alternatively, would it be possible to set `default-features = false` in your dependency configuration? That should disable this crate's `hashbrown` feature, which will cause the crate to use the standard library's hashmap instead of `hashbrown`'s.
